name: Moraco
favicon: null
layout_spectrum: 0.46591
typography_spectrum: 0.88616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d2446'
    - '#ffffff'
    - '#28638f'
    - '#82858a'
    - '#abb4bd'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
